apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: vortex
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: chamathrko/vortex:auth-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server.vortex:9999"
        - name: POST_SERVICE_URL
          value: "http://post-service.vortex:8300"
        - name: USER_SERVICE_URL
          value: "http://user-service.vortex:8200"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: vortex-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vortex
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
  type: ClusterIP
