apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: vortex
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: chamathrko/gateway-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
        env:
        - name: USER_SERVICE_URL
          value: "http://user-service.vortex:8200"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.vortex:8100"
        - name: POST_SERVICE_URL
          value: "http://post-service.vortex:8300"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.vortex:8400"
        - name: CONFIG_SERVER_URL
          value: "http://config-server.vortex:9999"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: vortex-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: vortex
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: TCP
    port: 8765
    targetPort: 8765
  type: ClusterIP


