apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: vortex
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: chamathrko/user-service:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.vortex:8100"
        - name: EUREKA_SERVER_URL
          value: "http://eureka-server.vortex:8761/eureka"
        - name: KAFKA_SERVER_URL
          value: "http://kafka-server.vortex:9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: vortex-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: vortex
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
  type: ClusterIP
